name: Build and Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build WAR
        run: mvn clean package
      - name: verify war
        run: ls -lh target/
        

      - name: Deploy WAR
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}

        run: |
          curl -u "$TOMCAT_USER:$TOMCAT_PASSWORD" \
            -T target/TrainBook-1.0.0-SNAPSHOT.war \
            "$TOMCAT_URL/deploy?path=/train-ticket-reservation&update=true"

          echo "Deployment completed"
